[package]
name = "metal-rs"
version = "0.6.5"
description = "Rust bindings for Metal"
documentation = "https://docs.rs/crate/metal-rs"
homepage = "https://github.com/gfx-rs/metal-rs"
repository = "https://github.com/gfx-rs/metal-rs"
authors = ["GFX Developers"]
readme = "README.md"
keywords = ["metal", "graphics", "bindings"]
license = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"

[dependencies]
cocoa = "0.13"
bitflags = "1"
libc = "0.2"
log = "0.4"
objc-foundation = "0.1"
objc_id = "0.1"
block = "0.1.5"
foreign-types = "0.3"

[dependencies.objc]
version = "0.2.1"
features = ["objc_exception"]

[dev-dependencies]
winit = "0.7"
sema = "0.1.4"

[[example]]
name = "window"
path = "examples/window/main.rs"

[[example]]
name = "library"
path = "examples/library/main.rs"

[[example]]
name = "reflection"
path = "examples/reflection/main.rs"

[[example]]
name = "caps"
path = "examples/caps/main.rs"

[[example]]
name = "argument-buffer"
path = "examples/argument-buffer/main.rs"

[[example]]
name = "compute"
path = "examples/compute/main.rs"

[[example]]
name = "embedded-lib"
path = "examples/compute/embedded-lib.rs"

[[example]]
name = "compute-argument-buffer"
path = "examples/compute/compute-argument-buffer.rs"
